name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -o ./bin/linux/turn ./src/turn.go

      - name: Test
        run: go test -v ./src/test/turn_basic_test.go
