name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        run: |
          go install github.com/floscodes/golang-thousands@latest
          go install github.com/gookit/color@latest
          go install github.com/hisamafahri/coco@latest
          go install github.com/jagottsicher/termcolor@latest

      - name: Build
        run: |
          cd src
          GOARCH=amd64 GOOS=linux go build -o ../bin/linux/turn ./turn.go

#      - name: Test
#        run: go test -v ./src/test/turn_basic_test.go
